# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0d24f165c2ac50979a7b0330eb593877f5d5f20b40e60b5364f80da9c63ccb7344cc85d01fbe12dd6072f30d1a4d7d85f391bf6e5904bf54b01ecb7752fe387

test:
  secret_key_base: 30fe8450f17a4d1bf9f69051d20fc51cb0a0ef283b03808523e6277b1cf23b637866e908fd1e7e2d6444806bacbc63d2b70831db5d5bcb76305441848ac33319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
